### PR TITLE
add hooks for serverless-offline support

### PR DESCRIPTION
**Pull request by softprops**
## What did you implement:

a story for testing lambdas locally easily still does not exist. serverless-offline is the defacto starndard for that in the serverless community. there are some hooks this plugin could add to make this easier

relates to https://github.com/softprops/serverless-rust/issues/74

Closes: #xxx

#### What (if anything) would need to be called out in the CHANGELOG for the next release:

### CODE REVIEW

**Comment by kuberlog** [comment]
Know of a way to recompile and reload without stopping serverless-offline? If I make changes, I have to restart the server.

**Comment by softprops** [comment]
I haven't been able to get serverless offline to work due to this bug https://github.com/dherault/serverless-offline/issues/1041

**Comment by softprops** [comment]
The hooks are in place but it seems a volume mount to a symlinked directory set up by serverless offline that is incompatible with docker for mac

**Comment by kuberlog** [comment]
Ah. I run linux, so I can at least get it to work as a 1 off. Can't recompile though.

**Comment by softprops** [comment]
Good to hear. I didn't looker deeper into thier docs when I hit the blocker. Let me know what you find.

**Pull request merged**
